# Generated by Django 5.2.7 on 2025-11-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_is_read_message_status_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='is_online',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_seen',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
